language: python
python:
  - "3.9"

branches:
  only:
  - master

addons:
  sonarcloud:
    organization: "switcherapi"
    token: ${SONAR_TOKEN}

jobs:
  include:
    - stage: compile and test
      install:
        - pip install -r requirements.txt
      script:
        - pytest -v --cov=./ --cov-report xml
        - sonar-scanner
    - stage: deploy
      if: type NOT IN (pull_request)
      script:
        - echo "Deploying to Production"
      
      before_deploy:
        - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.9.3
      deploy:
        provider: heroku
        app: switcher-slack-app
        api_key: ${HEROKU_KEY}

stages:
  - compile and test
  - deploy